springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/Springboot_DB
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: kramashia101@gmail.com
    password: ntdcyrtfshfdmaow
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

